name: CMake


on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

env:
  NSFINDSFML: 1

jobs:
  build:
    runs-on: ubuntu-latest
    name: Run CMake
    steps:
    - uses: actions/checkout@v3
      with:
        submodules: recursive

    - name: Install SFML
      run: sudo apt-get install libsfml-dev
      
    - name: Setup Cmake Build
      run: |
        mkdir build
        cd build
        cmake ..

    - name: Build
      # Build your program with the given configuration
      run: |
        cd build
        make
